#pragma once

namespace HipHop {

    enum class AssetType
    {
        Default = 0,

        ALST = 'ALST',
        ANIM = 'ANIM',
        ATBL = 'ATBL',
        ATKT = 'ATKT',
        BINK = 'BINK',
        BOUL = 'BOUL',
        BSP = 'BSP ',
        BUTN = 'BUTN',
        CAM = 'CAM ',
        CCRV = 'CCRV',
        CNTR = 'CNTR',
        COLL = 'COLL',
        COND = 'COND',
        CRDT = 'CRDT',
        CSN = 'CSN ',
        CSNM = 'CSNM',
        CSSS = 'CSSS',
        CTOC = 'CTOC',
        DEST = 'DEST',
        DPAT = 'DPAT',
        DSCO = 'DSCO',
        DSTR = 'DSTR',
        DTRK = 'DTRK',
        DUPC = 'DUPC',
        DYNA = 'DYNA',
        EGEN = 'EGEN',
        ENV = 'ENV ',
        FLY = 'FLY ',
        FOG = 'FOG ',
        GRSM = 'GRSM',
        GRUP = 'GRUP',
        GUST = 'GUST',
        HANG = 'HANG',
        JAW = 'JAW ',
        JSP = 'JSP ',
        LITE = 'LITE',
        LKIT = 'LKIT',
        LOBM = 'LOBM',
        LODT = 'LODT',
        MAPR = 'MAPR',
        MINF = 'MINF',
        MODL = 'MODL',
        MPHT = 'MPHT',
        MRKR = 'MRKR',
        MVPT = 'MVPT',
        NGMS = 'NGMS',
        NPC = 'NPC ',
        NPCS = 'NPCS',
        ONEL = 'ONEL',
        PARE = 'PARE',
        PARP = 'PARP',
        PARS = 'PARS',
        PEND = 'PEND',
        PGRS = 'PGRS',
        PICK = 'PICK',
        PIPT = 'PIPT',
        PKUP = 'PKUP',
        PLAT = 'PLAT',
        PLYR = 'PLYR',
        PORT = 'PORT',
        PRJT = 'PRJT',
        RANM = 'RANM',
        RAW = 'RAW ',
        RWTX = 'RWTX',
        SCRP = 'SCRP',
        SDFX = 'SDFX',
        SFX = 'SFX ',
        SGRP = 'SGRP',
        SHDW = 'SHDW',
        SHRP = 'SHRP',
        SIMP = 'SIMP',
        SLID = 'SLID',
        SND = 'SND ',
        SNDI = 'SNDI',
        SNDS = 'SNDS',
        SPLN = 'SPLN',
        SPLP = 'SPLP',
        SSET = 'SSET',
        SUBT = 'SUBT',
        SURF = 'SURF',
        TEXS = 'TEXS',
        TEXT = 'TEXT',
        TIMR = 'TIMR',
        TPIK = 'TPIK',
        TRIG = 'TRIG',
        TRWT = 'TRWT',
        UI = 'UI  ',
        UIFT = 'UIFT',
        UIM = 'UIM ',
        VIL = 'VIL ',
        VILP = 'VILP',
        VOLU = 'VOLU',
        WIRE = 'WIRE',
        ZLIN = 'ZLIN'
    };

}